<?php
require_once __DIR__.'/config.php';
require_permission('access_groups','view');
$resources=['dashboard'=>'داشبورد','buildings'=>'ساختمان‌ها','blocks'=>'بلوک‌ها','units'=>'واحدها','persons'=>'اشخاص','memberships'=>'اعضا','personnel'=>'پرسنل','contracts'=>'قراردادها','charges'=>'شارژها','payments'=>'پرداخت‌ها','reports'=>'گزارش‌ها','users'=>'کاربران','access_groups'=>'گروه‌های دسترسی','settings'=>'تنظیمات'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf(); $action=post('action');
 if($action==='save'){require_permission('access_groups','edit');$id=(int)post('id');$name=trim(post('name'));$desc=trim(post('description'))?:null;if(!$name){flash('نام گروه الزامی است.');redirect('access_groups.php');}
  if($id){$st=$pdo->prepare('SELECT is_system FROM access_groups WHERE id=?');$st->execute([$id]);$system=(bool)$st->fetchColumn();if($system){$name='administrators';} $pdo->prepare('UPDATE access_groups SET name=?,description=? WHERE id=?')->execute([$name,$desc,$id]);}
  else{$pdo->prepare('INSERT INTO access_groups(name,description) VALUES(?,?)')->execute([$name,$desc]);$id=(int)$pdo->lastInsertId();}
  foreach($resources as $key=>$label){$v=isset($_POST['p'][$key]['view']);$c=isset($_POST['p'][$key]['create']);$e=isset($_POST['p'][$key]['edit']);$d=isset($_POST['p'][$key]['delete']);$pdo->prepare('INSERT INTO permissions(group_id,resource,can_view,can_create,can_edit,can_delete) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE can_view=VALUES(can_view),can_create=VALUES(can_create),can_edit=VALUES(can_edit),can_delete=VALUES(can_delete)')->execute([$id,$key,$v,$c,$e,$d]);}
  log_activity('update','access_groups',$id,'ذخیره گروه و دسترسی‌ها');flash('گروه و دسترسی‌ها ذخیره شد.');redirect('access_groups.php');
 }
 if($action==='delete'){require_permission('access_groups','delete');$id=(int)post('id');$st=$pdo->prepare('SELECT name,is_system FROM access_groups WHERE id=?');$st->execute([$id]);$g=$st->fetch();if(!$g||$g['is_system']){flash('گروه administrators قابل حذف نیست.');redirect('access_groups.php');}$pdo->prepare('DELETE FROM access_groups WHERE id=?')->execute([$id]);flash('گروه حذف شد.');redirect('access_groups.php');}
}
$edit=null;$perms=[];
if(isset($_GET['edit'])){$id=(int)$_GET['edit'];$st=$pdo->prepare('SELECT * FROM access_groups WHERE id=?');$st->execute([$id]);$edit=$st->fetch();$st=$pdo->prepare('SELECT * FROM permissions WHERE group_id=?');$st->execute([$id]);foreach($st as $p)$perms[$p['resource']]=$p;}
$rows=$pdo->query('SELECT g.*,COUNT(DISTINCT u.id) user_count FROM access_groups g LEFT JOIN users u ON u.access_group_id=g.id GROUP BY g.id ORDER BY g.is_system DESC,g.name')->fetchAll();
page_header('گروه‌های دسترسی');
?>
<div class="content-header mb-4"><div><h4 class="mb-1">گروه‌های دسترسی</h4><p class="text-muted mb-0">مجوزهای مشاهده، ایجاد، ویرایش و حذف برای هر بخش.</p></div><a class="btn btn-primary" href="access_groups.php?new=1">گروه جدید</a></div>
<?php if(isset($_GET['new'])||$edit):?><div class="card mb-4"><div class="card-body"><h6 class="card-title mb-4"><?=($edit?'ویرایش گروه':'ایجاد گروه')?></h6><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="save"><?php if($edit):?><input type="hidden" name="id" value="<?=$edit['id']?>"><?php endif;?><div class="row"><div class="col-md-4 form-group"><label>نام گروه</label><input class="form-control" name="name" required value="<?=e($edit['name']??'')?>"></div><div class="col-md-8 form-group"><label>توضیحات</label><input class="form-control" name="description" value="<?=e($edit['description']??'')?>"></div></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>بخش</th><th>مشاهده</th><th>ایجاد</th><th>ویرایش</th><th>حذف</th></tr></thead><tbody><?php foreach($resources as $key=>$label):$p=$perms[$key]??[];?><tr><td><?=e($label)?></td><?php foreach(['view','create','edit','delete'] as $a):?><td><div class="custom-control custom-checkbox"><input type="checkbox" class="custom-control-input" id="<?=$key?>_<?=$a?>" name="p[<?=$key?>][<?=$a?>]" <?=!empty($p['can_'.$a])?'checked':''?>><label class="custom-control-label" for="<?=$key?>_<?=$a?>"></label></div></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><button class="btn btn-primary">ذخیره</button> <a class="btn btn-outline-secondary" href="access_groups.php">انصراف</a></form></div></div><?php endif;?>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover"><thead><tr><th>گروه</th><th>توضیحات</th><th>کاربران</th><th>عملیات</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['name'])?></td><td><?=e($r['description'])?></td><td><?=$r['user_count']?></td><td><a class="btn btn-sm btn-outline-primary" href="access_groups.php?edit=<?=$r['id']?>">ویرایش دسترسی</a><?php if(!$r['is_system']):?><form method="post" class="d-inline" onsubmit="return confirm('حذف شود؟')"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-outline-danger">حذف</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<?php page_footer(); ?>