CREATE DATABASE IF NOT EXISTS borjino CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE borjino;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(150) NOT NULL DEFAULT '',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS buildings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  postal_code VARCHAR(20) DEFAULT NULL,
  building_type ENUM('residential','commercial','office','educational','other') NOT NULL DEFAULT 'residential',
  construction_date DATE DEFAULT NULL,
  parking_count INT NOT NULL DEFAULT 0,
  storage_count INT NOT NULL DEFAULT 0,
  province VARCHAR(100) DEFAULT NULL,
  city VARCHAR(100) DEFAULT NULL,
  address VARCHAR(500) DEFAULT NULL,
  manager_name VARCHAR(150) DEFAULT NULL,
  manager_phone VARCHAR(50) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS blocks (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  building_id INT UNSIGNED NOT NULL,
  block_no VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  floor_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(building_id) REFERENCES buildings(id) ON DELETE CASCADE,
  INDEX(building_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS units (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  building_id INT UNSIGNED NOT NULL,
  block_id INT UNSIGNED NOT NULL,
  unit_no VARCHAR(50) NOT NULL,
  floor_no INT NOT NULL DEFAULT 0,
  area DECIMAL(12,2) NOT NULL DEFAULT 0,
  parking_count INT NOT NULL DEFAULT 0,
  parking_numbers VARCHAR(500) DEFAULT NULL,
  storage_count INT NOT NULL DEFAULT 0,
  storage_numbers VARCHAR(500) DEFAULT NULL,
  status ENUM('vacant','repair','occupied','rented','sold') NOT NULL DEFAULT 'vacant',
  financial_status ENUM('debtor','creditor','settled') NOT NULL DEFAULT 'settled',
  direction ENUM('north','south','east','west') DEFAULT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(building_id) REFERENCES buildings(id) ON DELETE CASCADE,
  FOREIGN KEY(block_id) REFERENCES blocks(id) ON DELETE CASCADE,
  UNIQUE KEY uq_block_unit(block_id,unit_no),
  INDEX(building_id),
  INDEX(block_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS persons (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  national_code VARCHAR(20) DEFAULT NULL,
  mobile VARCHAR(50) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  address VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS memberships (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  unit_id INT UNSIGNED NOT NULL,
  person_id INT UNSIGNED NOT NULL,
  role ENUM('owner','tenant','resident','family','other') NOT NULL DEFAULT 'resident',
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE CASCADE,
  FOREIGN KEY(person_id) REFERENCES persons(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS contracts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  unit_id INT UNSIGNED NOT NULL,
  person_id INT UNSIGNED NOT NULL,
  type ENUM('rent','sale') NOT NULL DEFAULT 'rent',
  start_date DATE NOT NULL,
  end_date DATE DEFAULT NULL,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  deposit_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  notes TEXT,
  FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE CASCADE,
  FOREIGN KEY(person_id) REFERENCES persons(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS charges (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  unit_id INT UNSIGNED NOT NULL,
  title VARCHAR(200) NOT NULL,
  period VARCHAR(20) NOT NULL,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  due_date DATE DEFAULT NULL,
  status ENUM('unpaid','partial','paid') NOT NULL DEFAULT 'unpaid',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS payments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  charge_id INT UNSIGNED NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  paid_at DATE NOT NULL,
  method VARCHAR(50) DEFAULT 'cash',
  reference_no VARCHAR(100) DEFAULT NULL,
  notes TEXT,
  FOREIGN KEY(charge_id) REFERENCES charges(id) ON DELETE CASCADE
) ENGINE=InnoDB;
