<?php
require_once __DIR__.'/config.php'; require_page_permission('units');
function unit_status_label($v){return ['vacant'=>'خالی','repair'=>'در حال تعمیر','occupied'=>'ساکن','rented'=>'اجاره داده شده','sold'=>'فروخته شده'][$v]??$v;}
function financial_label($v){return ['debtor'=>'بدهکار','creditor'=>'بستانکار','settled'=>'تسویه'][$v]??$v;}

if(isset($_GET['delete'])){$id=(int)$_GET['delete'];$st=$pdo->prepare('SELECT COUNT(*) FROM memberships WHERE unit_id=?');$st->execute([$id]);if((int)$st->fetchColumn()>0){flash('این واحد ساکن/عضو متصل دارد و قابل حذف نیست.');redirect('units.php');}$pdo->prepare('DELETE FROM units WHERE id=?')->execute([$id]);flash('واحد حذف شد.');redirect('units.php');}

if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf(); $action=post('action'); $building_id=(int)post('building_id'); $block_id=(int)post('block_id');
 $st=$pdo->prepare('SELECT * FROM blocks WHERE id=? AND building_id=?');$st->execute([$block_id,$building_id]);$block=$st->fetch();if(!$block){flash('ساختمان و بلوک انتخاب‌شده معتبر نیست.');redirect('units.php');}
 $insert=function($floor,$no)use($pdo,$building_id,$block_id){$q=$pdo->prepare('INSERT INTO units(building_id,block_id,unit_no,unit_postal_code,floor_no,area,parking_count,parking_numbers,storage_count,storage_numbers,status,financial_status,direction,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$building_id,$block_id,(string)$no,trim(post('unit_postal_code'))?:null,$floor,(float)post('area',0),(int)post('parking_count',0),trim(post('parking_numbers'))?:null,(int)post('storage_count',0),trim(post('storage_numbers'))?:null,post('status','vacant'),post('financial_status','settled'),post('direction')?:null,trim(post('notes'))?:null]);};
 try{
  if($action==='block_group'){$fs=max(1,(int)post('floor_start',1));$fe=max($fs,(int)post('floor_end',$fs));if($fe>(int)$block['floor_count'])throw new Exception('طبقه انتخابی بیشتر از تعداد طبقات بلوک است.');$count=max(1,(int)post('units_per_floor',1));$next=max(0,(int)post('number_start',1));for($f=$fs;$f<=$fe;$f++)for($n=0;$n<$count;$n++)$insert($f,$next++);flash('واحدهای بلوک به‌صورت گروهی ساخته شدند.');}
  elseif($action==='floor_group'){$floor=max(1,(int)post('floor_no',1));if($floor>(int)$block['floor_count'])throw new Exception('طبقه انتخابی بیشتر از تعداد طبقات بلوک است.');$count=max(1,(int)post('unit_count',1));$next=max(0,(int)post('number_start',1));for($n=0;$n<$count;$n++)$insert($floor,$next++);flash('واحدهای طبقه به‌صورت گروهی ساخته شدند.');}
  elseif($action==='single'){$id=(int)post('id');$unit_no=trim(post('unit_no'));$floor=max(0,(int)post('floor_no'));if($id){$q=$pdo->prepare('UPDATE units SET building_id=?,block_id=?,unit_no=?,unit_postal_code=?,floor_no=?,area=?,parking_count=?,parking_numbers=?,storage_count=?,storage_numbers=?,status=?,financial_status=?,direction=?,notes=? WHERE id=?');$q->execute([$building_id,$block_id,$unit_no,trim(post('unit_postal_code'))?:null,$floor,(float)post('area',0),(int)post('parking_count',0),trim(post('parking_numbers'))?:null,(int)post('storage_count',0),trim(post('storage_numbers'))?:null,post('status','vacant'),post('financial_status','settled'),post('direction')?:null,trim(post('notes'))?:null,$id]);flash('واحد ویرایش شد.');}else{$insert($floor,$unit_no);flash('واحد اضافه شد.');}}
 }catch(Throwable $e){flash('خطا در ساخت واحد: '.($e->getCode()===23000?'شماره واحد تکراری است.':$e->getMessage()));}
 redirect('units.php');
}
$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM units WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$buildings=$pdo->query('SELECT id,name FROM buildings ORDER BY name')->fetchAll();$blocks=$pdo->query('SELECT b.*,g.name building_name FROM blocks b JOIN buildings g ON g.id=b.building_id ORDER BY g.name,b.name')->fetchAll();$rows=$pdo->query('SELECT u.*,g.name building_name,b.name block_name FROM units u JOIN buildings g ON g.id=u.building_id JOIN blocks b ON b.id=u.block_id ORDER BY g.name,b.name,u.floor_no,CAST(u.unit_no AS UNSIGNED),u.unit_no')->fetchAll();page_header('واحدها');
?>
<div class="content-header mb-4"><div><h4 class="mb-1">مدیریت واحدها</h4><p class="text-muted mb-0">سه روش ایجاد واحد مطابق مشخصات فنی سامانه.</p></div></div>
<div class="card mb-4"><div class="card-body"><ul class="nav nav-tabs mb-4"><li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#blockGroup">۱. گروهی در سطح بلوک</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#floorGroup">۲. گروهی در سطح طبقه</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#single">۳. ایجاد تکی</a></li></ul><div class="tab-content">
<div class="tab-pane fade show active" id="blockGroup"><form method="post"><input type="hidden" name="action" value="block_group"><?=csrf_field()?><div class="row">
<div class="col-md-3 form-group"><label>ساختمان</label><select class="form-control" name="building_id" required><?php foreach($buildings as $b):?><option value="<?=$b['id']?>"><?=e($b['name'])?></option><?php endforeach;?></select></div><div class="col-md-3 form-group"><label>بلوک</label><select class="form-control" name="block_id" required><?php foreach($blocks as $b):?><option value="<?=$b['id']?>"><?=e($b['building_name'].' / '.$b['name'])?> (<?=$b['floor_count']?> طبقه)</option><?php endforeach;?></select></div>
<div class="col-md-3 form-group"><label>از طبقه</label><input class="form-control" type="number" min="1" name="floor_start" value="1"></div><div class="col-md-3 form-group"><label>تا طبقه</label><input class="form-control" type="number" min="1" name="floor_end" value="1"></div><div class="col-md-3 form-group"><label>تعداد واحد در هر طبقه</label><input class="form-control" type="number" min="1" name="units_per_floor" value="1"></div><div class="col-md-3 form-group"><label>پیششماره / شماره شروع</label><input class="form-control" type="number" min="0" name="number_start" value="1"></div>
<?php include __DIR__.'/includes/unit_common_fields.php'; ?>
</div><button class="btn btn-primary">ساخت واحدها</button></form></div>
<div class="tab-pane fade" id="floorGroup"><form method="post"><input type="hidden" name="action" value="floor_group"><?=csrf_field()?><div class="row">
<div class="col-md-3 form-group"><label>ساختمان</label><select class="form-control" name="building_id" required><?php foreach($buildings as $b):?><option value="<?=$b['id']?>"><?=e($b['name'])?></option><?php endforeach;?></select></div><div class="col-md-3 form-group"><label>بلوک</label><select class="form-control" name="block_id" required><?php foreach($blocks as $b):?><option value="<?=$b['id']?>"><?=e($b['building_name'].' / '.$b['name'])?> (<?=$b['floor_count']?> طبقه)</option><?php endforeach;?></select></div><div class="col-md-3 form-group"><label>طبقه</label><input class="form-control" type="number" min="1" name="floor_no" value="1"></div><div class="col-md-3 form-group"><label>تعداد واحد در این طبقه</label><input class="form-control" type="number" min="1" name="unit_count" value="1"></div><div class="col-md-3 form-group"><label>پیششماره / شماره شروع</label><input class="form-control" type="number" min="0" name="number_start" value="1"></div>
<?php include __DIR__.'/includes/unit_common_fields.php'; ?></div><button class="btn btn-primary">ساخت واحدهای این طبقه</button></form></div>
<div class="tab-pane fade" id="single"><form method="post"><input type="hidden" name="action" value="single"><?=csrf_field()?><?php if($edit):?><input type="hidden" name="id" value="<?=$edit['id']?>"><?php endif;?><div class="row">
<div class="col-md-3 form-group"><label>ساختمان</label><select class="form-control" name="building_id" required><?php foreach($buildings as $b):?><option value="<?=$b['id']?>" <?=($edit['building_id']??'')==$b['id']?'selected':''?>><?=e($b['name'])?></option><?php endforeach;?></select></div><div class="col-md-3 form-group"><label>بلوک</label><select class="form-control" name="block_id" required><?php foreach($blocks as $b):?><option value="<?=$b['id']?>" <?=($edit['block_id']??'')==$b['id']?'selected':''?>><?=e($b['building_name'].' / '.$b['name'])?></option><?php endforeach;?></select></div><div class="col-md-3 form-group"><label>شماره واحد</label><input class="form-control" name="unit_no" required value="<?=e($edit['unit_no']??'')?>"></div><div class="col-md-3 form-group"><label>کد پستی واحد</label><input class="form-control" name="unit_postal_code" value="<?=e($edit['unit_postal_code']??'')?>"></div><div class="col-md-3 form-group"><label>طبقه</label><input class="form-control" type="number" name="floor_no" value="<?=$edit['floor_no']??0?>"></div>
<?php include __DIR__.'/includes/unit_common_fields.php'; ?><div class="col-md-12 form-group"><label>توضیحات</label><textarea class="form-control" name="notes" rows="3"><?=e($edit['notes']??'')?></textarea></div></div><button class="btn btn-primary">ذخیره واحد</button> <a class="btn btn-outline-secondary" href="units.php">انصراف</a></form></div>
</div></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>ساختمان</th><th>بلوک</th><th>واحد</th><th>طبقه</th><th>متراژ</th><th>وضعیت</th><th>مالی</th><th>عملیات</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['building_name'])?></td><td><?=e($r['block_name'])?></td><td><strong><?=e($r['unit_no'])?></strong></td><td><?=$r['floor_no']?></td><td><?=$r['area']?></td><td><?=e(unit_status_label($r['status']))?></td><td><?=e(financial_label($r['financial_status']))?></td><td><a class="btn btn-sm btn-outline-primary" href="units.php?edit=<?=$r['id']?>#single">ویرایش</a> <a class="btn btn-sm btn-outline-danger" onclick="return confirm('حذف شود؟')" href="units.php?delete=<?=$r['id']?>">حذف</a></td></tr><?php endforeach;?></tbody></table></div></div></div>
<?php page_footer(); ?>
