<?php

declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\BlockController;
use App\Controllers\BuildingController;
use App\Controllers\ContractController;
use App\Controllers\DashboardController;
use App\Controllers\HomeController;
use App\Controllers\PersonController;
use App\Controllers\UnitController;
use App\Controllers\UnitMembershipController;
use App\Database\Connection;
use App\Middleware\AuthMiddleware;
use App\Repositories\BlockRepository;
use App\Repositories\BuildingRepository;
use App\Repositories\ContractRepository;
use App\Repositories\PersonRepository;
use App\Repositories\UnitMembershipRepository;
use App\Repositories\UnitRepository;
use App\Repositories\UserRepository;
use App\Services\AuthService;
use App\Support\Router;
use App\Support\View;

$router = new Router();
$view = new View(dirname(__DIR__) . '/resources/views');
$connection = new Connection(require dirname(__DIR__) . '/config/database.php');
$pdo = $connection->getPdo();
$userRepository = new UserRepository($pdo);
$authService = new AuthService($userRepository);
$authMiddleware = new AuthMiddleware($authService);
$buildingRepository = new BuildingRepository($pdo);
$blockRepository = new BlockRepository($pdo);
$unitRepository = new UnitRepository($pdo);
$personRepository = new PersonRepository($pdo);
$membershipRepository = new UnitMembershipRepository($pdo);
$contractRepository = new ContractRepository($pdo);

$homeController = new HomeController($view);
$authController = new AuthController($view, $authService);
$dashboardController = new DashboardController($view, $authMiddleware, $authService);
$buildingController = new BuildingController($view, $buildingRepository, $authMiddleware);
$blockController = new BlockController($view, $blockRepository, $buildingRepository, $authMiddleware);
$unitController = new UnitController($view, $unitRepository, $buildingRepository, $blockRepository, $authMiddleware);
$personController = new PersonController($view, $personRepository, $authMiddleware);
$membershipController = new UnitMembershipController($view, $membershipRepository, $personRepository, $unitRepository, $authMiddleware);
$contractController = new ContractController($view, $contractRepository, $personRepository, $unitRepository, $authMiddleware);

$router->get('/', [$homeController, 'index']);
$router->get('/login', [$authController, 'showLogin']);
$router->post('/login', [$authController, 'login']);
$router->post('/logout', [$authController, 'logout']);
$router->get('/dashboard', [$dashboardController, 'index']);
$router->get('/buildings', [$buildingController, 'index']);
$router->get('/buildings/create', [$buildingController, 'create']);
$router->post('/buildings/store', [$buildingController, 'store']);
$router->get('/buildings/edit', [$buildingController, 'edit']);
$router->post('/buildings/update', [$buildingController, 'update']);
$router->post('/buildings/delete', [$buildingController, 'delete']);
$router->get('/blocks', [$blockController, 'index']);
$router->get('/blocks/create', [$blockController, 'create']);
$router->post('/blocks/store', [$blockController, 'store']);
$router->get('/blocks/edit', [$blockController, 'edit']);
$router->post('/blocks/update', [$blockController, 'update']);
$router->post('/blocks/delete', [$blockController, 'delete']);
$router->get('/units', [$unitController, 'index']);
$router->get('/units/create', [$unitController, 'create']);
$router->post('/units/store', [$unitController, 'store']);
$router->get('/units/edit', [$unitController, 'edit']);
$router->post('/units/update', [$unitController, 'update']);
$router->post('/units/delete', [$unitController, 'delete']);
$router->get('/units/generate', [$unitController, 'generate']);
$router->post('/units/generate', [$unitController, 'generateStore']);
$router->get('/persons', [$personController, 'index']);
$router->get('/persons/create', [$personController, 'create']);
$router->post('/persons/store', [$personController, 'store']);
$router->get('/persons/edit', [$personController, 'edit']);
$router->post('/persons/update', [$personController, 'update']);
$router->post('/persons/delete', [$personController, 'delete']);
$router->get('/unit-memberships', [$membershipController, 'index']);
$router->get('/unit-memberships/create', [$membershipController, 'create']);
$router->post('/unit-memberships/store', [$membershipController, 'store']);
$router->get('/unit-memberships/edit', [$membershipController, 'edit']);
$router->post('/unit-memberships/update', [$membershipController, 'update']);
$router->post('/unit-memberships/delete', [$membershipController, 'delete']);
$router->get('/contracts', [$contractController, 'index']);
$router->get('/contracts/create', [$contractController, 'create']);
$router->post('/contracts/store', [$contractController, 'store']);
$router->get('/contracts/edit', [$contractController, 'edit']);
$router->post('/contracts/update', [$contractController, 'update']);
$router->post('/contracts/delete', [$contractController, 'delete']);

return $router;
