<div class="col-md-3 form-group"><label>کد پستی واحد</label><input class="form-control" name="unit_postal_code" value="<?=e($edit['unit_postal_code']??'')?>"></div>
<div class="col-md-3 form-group"><label>متراژ<?=isset($action)&&$action!=='single'?' پیشفرض':''?></label><input class="form-control" type="number" step="0.01" name="area" value="<?=$edit['area']??0?>"></div>
<div class="col-md-3 form-group"><label>تعداد پارکینگ<?=isset($action)&&$action!=='single'?' پیشفرض':''?></label><input class="form-control" type="number" min="0" name="parking_count" value="<?=$edit['parking_count']??0?>"></div>
<div class="col-md-3 form-group"><label>شماره پارکینگ‌ها</label><input class="form-control" name="parking_numbers" value="<?=e($edit['parking_numbers']??'')?>" placeholder="مثلاً ۱،۲"></div>
<div class="col-md-3 form-group"><label>تعداد انبار<?=isset($action)&&$action!=='single'?' پیشفرض':''?></label><input class="form-control" type="number" min="0" name="storage_count" value="<?=$edit['storage_count']??0?>"></div>
<div class="col-md-3 form-group"><label>شماره انبارها</label><input class="form-control" name="storage_numbers" value="<?=e($edit['storage_numbers']??'')?>" placeholder="مثلاً ۱۰،۱۱"></div>
<div class="col-md-3 form-group"><label>وضعیت اولیه</label><select class="form-control" name="status"><?php foreach(['vacant'=>'خالی','repair'=>'در حال تعمیر','occupied'=>'ساکن','rented'=>'اجاره داده شده','sold'=>'فروخته شده'] as $k=>$v):?><option value="<?=$k?>" <?=($edit['status']??'vacant')===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></div>
<div class="col-md-3 form-group"><label>وضعیت مالی</label><select class="form-control" name="financial_status"><?php foreach(['settled'=>'تسویه','debtor'=>'بدهکار','creditor'=>'بستانکار'] as $k=>$v):?><option value="<?=$k?>" <?=($edit['financial_status']??'settled')===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></div>
<div class="col-md-3 form-group"><label>جهت</label><select class="form-control" name="direction"><option value="">بدون تعیین</option><?php foreach(['north'=>'شمالی','south'=>'جنوبی','east'=>'شرقی','west'=>'غربی'] as $k=>$v):?><option value="<?=$k?>" <?=($edit['direction']??'')===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></div>
<div class="col-md-12 form-group"><label>توضیحات مشترک</label><textarea class="form-control" name="notes" rows="2"><?=e($edit['notes']??'')?></textarea></div>
